version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dmm-practice
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /var/tmp
    environment:
      RAILS_ENV: development
    ports:
      - 3400:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      - dmm

  db:
    image: postgres:9.6.2-alpine
    container_name: dmm-database
    environment:
      POSTGRES_PASSWORD: 12345678
      TZ: "Asia/Tokyo"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    networks:
      - dmm

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_LISTEN_PORT: 80
    ports:
    - 8085:80
    depends_on:
      - db
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
    networks:
      - dmm

networks:
  dmm:

volumes:
  pg-data:
  pgadmin-data:

